# Generated by Django 4.2.1 on 2023-05-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_publisher_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
