# Generated by Django 4.2.1 on 2023-05-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Изданиe', 'verbose_name_plural': 'Издания'},
        ),
    ]
