# Generated by Django 4.2.1 on 2023-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_publisher_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='languages',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], max_length=2),
        ),
    ]
