# Generated by Django 4.2.1 on 2023-05-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('PostTag', models.ManyToManyField(related_name='tags', to='PostTag.post')),
            ],
        ),
    ]
