# Generated by Django 4.2.1 on 2023-05-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('languages', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], default=None, max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='PostTag',
        ),
        migrations.AddField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(related_name='tags', to='PostTag.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='PostTag.category'),
        ),
    ]
