# Generated by Django 4.2.1 on 2023-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0003_category_alter_post_options_remove_tag_posttag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(related_name='posts', to='PostTag.tag'),
        ),
    ]
