# Generated by Django 4.2.1 on 2023-06-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0006_alter_post_posttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PostTag.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
