# Generated by Django 4.2.1 on 2023-06-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0007_alter_post_category_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='languages',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
