# Generated by Django 4.2.1 on 2023-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0008_alter_category_languages_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='PostTag.tag'),
        ),
    ]
