# Generated by Django 4.2.1 on 2023-06-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0014_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
