# Generated by Django 4.2.1 on 2023-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTag', '0016_categorypost_post_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
